### ISSUE TITLE
Trying a build, failing, possible `ldconfig` issue

### ISSUE THREAD

**Issue by elboulangero** [pygobject/pgi-docgen#146]
Hi,

I'm just getting started with `pgi-docgen`. So I first installed `virtualenv` (might be good to mention this dependency in the README for guys like me who're just discovering the Python's world).

    $ sudo apt-get virtualenv

Done, OK. Then I followed your indications to setup the virtual environment.

    $ PYTHON=python2 source ./tools/bootstrap.sh

Ok. I see in the prompt that I'm within the virtual environment. Let's check where's Python.

    $ which python
    /home/art/Work/src/pgi-docgen/_venv/bin/python

Ok, it all looks good. Now let's get started by building the most basic documentation.

```
$ ./tools/build.sh GLib-2.0
GLib-2.0: building...
Traceback (most recent call last):
  File "./pgi-docgen.py", line 27, in <module>
    sys.exit(main(sys.argv))
  File "/home/art/Work/src/pgi-docgen/pgidocgen/create.py", line 67, in main
    gen.write(args.target)
  File "/home/art/Work/src/pgi-docgen/pgidocgen/gen/module.py", line 124, in write
    self._write(sub_dir, namespace, version)
  File "/home/art/Work/src/pgi-docgen/pgidocgen/gen/module.py", line 132, in _write
    module = Repository(namespace, version).parse()
  File "/home/art/Work/src/pgi-docgen/pgidocgen/repo.py", line 37, in parse
    return Module.from_repo(self)
  File "/home/art/Work/src/pgi-docgen/pgidocgen/docobj.py", line 1063, in from_repo
    symbol_mapping = SymbolMapping.from_module(repo, pymod)
  File "/home/art/Work/src/pgi-docgen/pgidocgen/docobj.py", line 924, in from_module
    source_map = repo.get_source_map()
  File "/home/art/Work/src/pgi-docgen/pgidocgen/repo.py", line 191, in get_source_map
    return self._ns.source_map
  File "/home/art/Work/src/pgi-docgen/pgidocgen/util.py", line 587, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/art/Work/src/pgi-docgen/pgidocgen/namespace.py", line 192, in source_map
    for symbol, path in get_line_numbers_for_name(lib).iteritems():
  File "/home/art/Work/src/pgi-docgen/pgidocgen/debug.py", line 304, in get_line_numbers_for_name
    for path in get_debug_files_for_name(library_name):
  File "/home/art/Work/src/pgi-docgen/pgidocgen/debug.py", line 120, in get_debug_files_for_name
    library_path = get_abs_library_path(library_name)
  File "/home/art/Work/src/pgi-docgen/pgidocgen/debug.py", line 283, in get_abs_library_path
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Not OK anymore ! Not sure what's going on, but if I look into `pgidocgen/debug.py` line 283, what I see is:

    data = subprocess.check_output(["ldconfig", "-p"], stderr=subprocess.STDOUT)

On my system (Debian 9), `ldconfig` is installed in `/sbin`, so it's not in the path for a normal user. Seems like it' s the issue here.

**Comment by lazka** [comment]
Thanks. What about now?

There might be more things broken as I haven't tested the virtualenv steps in some time and I'm not sure there are any users besides me using this and some code might make assumptions on my dev environment. For example I've added /sbin to my PATH in Debian.

**Comment by elboulangero** [comment]
It works now. I've got warnings here and there, but nothing fatal, and it's related to the doc building process.

```
$ ./tools/build.sh GLib-2.0
GLib-2.0: building...
Queue build for GLib-2.0
Build started for GLib-2.0
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/classes/BookmarkFile.rst:0: WARNING: Unknown target name: "exec".
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/classes/MainContext.rst:0: WARNING: Unknown target name: "timeout".
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/classes/TimeVal.rst:0: WARNING: Unknown target name: "time".
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/functions.rst:0: WARNING: Unknown target name: "time".
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/classes/DateTime.rst:759: WARNING: py:func reference target not found: GLib.DateTime.signals.z
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/classes/TimeZone.rst:88: WARNING: py:data reference target not found: GLib.TimeZone.props.mm
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/classes/TimeZone.rst:88: WARNING: py:data reference target not found: GLib.TimeZone.props.ss
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/flags.rst:266: WARNING: py:class reference target not found: GObject.GFlags
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/functions.rst:2230: WARNING: py:obj reference target not found: GLib.Error.free
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/functions.rst:5593: WARNING: py:obj reference target not found: event_source_id
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/functions.rst:9796: WARNING: py:obj reference target not found: GObject.GType
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/functions.rst:13200: WARNING: py:obj reference target not found: GObject.GType
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/mapping.rst:435: WARNING: py:data reference target not found: GLib.Error.copy
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/mapping.rst:435: WARNING: py:data reference target not found: GLib.Error.free
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/mapping.rst:605: WARNING: py:data reference target not found: GLib.Hook.destroy
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/mapping.rst:2390: WARNING: py:data reference target not found: GLib.VariantIter.free
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/mapping.rst:2390: WARNING: py:data reference target not found: GLib.VariantIter.n_children
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/mapping.rst:2390: WARNING: py:data reference target not found: GLib.VariantIter.next_value
/home/art/Work/src/pgi-docgen/_docs/GLib-2.0/mapping.rst:2645: WARNING: py:data reference target not found: GLib.mpn
GLib-2.0 finished: 1/1 done
All done
```

**Comment by lazka** [comment]
The warnings are normal. In some cases they are bugs/unsupported in pgi-docgen, in some cases they are out of date references in the docs, and things like above where GLib references  "GObject.GType", but GObject depends on GLib and can't be build before.

**Comment by elboulangero** [comment]
Ok, thanks for the details !
