### ISSUE TITLE
Cron failed

### ISSUE THREAD

**Issue by lazka** [pygobject/pgi-docgen#191]
https://dev.azure.com/pygobject/pgi-docgen/_build/results?buildId=287&view=logs&j=a6fe42f4-2b81-59e8-5c7c-1a0db487583c&t=a2461212-c2f7-552e-01c2-ba4f2fa5121a&l=466

For GUPnP-1.2

```
Traceback (most recent call last):
  File "./pgi-docgen", line 14, in <module>
    sys.exit(main(sys.argv))
  File "/home/user/app/pgidocgen/main.py", line 29, in main
    return args.func(args)
  File "/home/user/app/pgidocgen/create.py", line 61, in main
    gen.write(args.target)
  File "/home/user/app/pgidocgen/gen/module.py", line 129, in write
    mods = get_to_write(dir_, self._namespace, self._version)
  File "/home/user/app/pgidocgen/gen/module.py", line 122, in get_to_write
    ns = get_namespace(namespace, version)
  File "/home/user/app/pgidocgen/namespace.py", line 50, in get_namespace
    getattr(ns, k)
  File "/home/user/app/pgidocgen/util.py", line 605, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/home/user/app/pgidocgen/namespace.py", line 171, in shadow_map
    self._ensure_types()
  File "/home/user/app/pgidocgen/namespace.py", line 160, in _ensure_types
    _parse_types(dom, self.import_module(), self.namespace)
  File "/home/user/app/pgidocgen/namespace.py", line 406, in _parse_types
    assert not all_shadowed_by
AssertionError
```

**Comment by lazka** [comment]
Fixed in 701c4390b7912a4e6723e1
